FROM gcc:latest

WORKDIR /app/store

COPY store/*.c store/
COPY store/*.h store/
COPY store/test.c store/

# Build the key-value store
RUN mkdir /app/build \
 && gcc -o /app/build/store store/*.c

CMD ["/app/build/store"]
